# Use the official Node.js image as the base image for backend
FROM node:20.0.0-alpine AS backend

# Set the working directory for frontend
WORKDIR /app/quirknotes/backend

# Copy backend package files to the working directory
COPY quirknotes/backend/package*.json ./

# Install the backend dependencies
RUN npm install

# Copy the backend source code to the working directory
COPY quirknotes/backend/ ./

# Expose the port 4000 for the backend
EXPOSE 4000

# Start the backend server
CMD ["npm", "start"]